### ISSUE TITLE
Black site / Gray panel is WebOS TV browser 

### ISSUE THREAD

**Issue by SeeJayDee** [mateussouzaweb/crunchyroll-webos#10]
Like in previous issue (#4?) the website link doesn't display anything usable.

I'm using LG UJ654T with WebOS version 6.00.15

**Comment by Informatic** [comment]
That TV is running webOS TV 3.5 series (same as mine, 3.8 here - 06.00.15 is "firmware version") - based on Chromium 38.

**Comment by Informatic** [comment]
OK, so far seems like the biggest issue is lack of support for async functions, and use of `const` with strict mode in `vanilla.js`. This probably sounds kind of like a job for babel.

**Comment by mateussouzaweb** [comment]
@Informatic even with compilation to ES5, WebOS TV 3.X will not work because the video player only works on Chromium 39+
@SeeJayDee can you check again with this new version (1.6.0)?

**Comment by Informatic** [comment]
Which videoplayer do you mean? iiuc `src/js/video.js` is using plain html5 video + hlsjs - both of which (after sufficient babelization of hlsjs) should work fine on webOS TV 3.x/Chromium 38.

**Comment by Informatic** [comment]
I don't know honestly what HLS.js claim is based on.

One thing I am absolutely sure about is that Plyr+HLS.js-based streaming in [streamkatze](https://github.com/Informatic/streamkatze/blob/main/src/views/PlayStream.js) works very well on webOS 3.x/Chromium 38. And I am also pretty sure that it was in fact using HLS.js, and not webOS built-in HLS support, since that was utterly broken on streams hosted by media.ccc.de, causing media pipeline process/browser crashes :P

**Comment by mateussouzaweb** [comment]
Understood chief, maybe it could work then :D

I sent today a new version (1.8.0), it's not compiled with babel, but I believe that will work since typescript is compiling it to ES3. We just need to implement a polyfill to fetch API...

Can someone confirm if at least the login view is displayed? WebOS 3.0 emulator sucks too much, I can do a decent test...

**Comment by DarkestMessiah** [comment]
I own a SJ800V with WebOS 3.5 and it still shows a black screen with a grey sidebar

**Comment by DarkestMessiah** [comment]
I own a SJ800V with WebOS 3.5 I think (firmware 6.00.25) and the app displays a black screen with a grey sidebar

**Comment by l0st1d0l** [comment]
Same problem here, only a black screen with a grey sidebar without even the login info

LJ551C / 06.00.10

**Comment by Dorianblack97** [comment]
Same problem with UJ750V / 06.00.25

**Comment by aisrum21** [comment]
Same problem with UJ634V / 3.6.0-62906

**Comment by DarkestMessiah** [comment]
I just updated the app and tried it again, it finally works!! Thank you so much, you guys are the best!
