### ISSUE TITLE
[REQUEST] Resolution selection 

### ISSUE THREAD

**Issue by KriyenKP** [mateussouzaweb/crunchyroll-webos#2]
There doesn't seem to be a way to set a resolution manually. Or am i missing something? My internet is fast but have a limited data allowance.

**Comment by mateussouzaweb** [comment]
There is no way of do this... when I am watching, it starts in low resolution, but the player automatically detects the best resolution and change it for me... I even get better quality than their official website (I think is premium subscription quality, but I have not premium).

**Comment by Bebooo43** [comment]
Could you please add the ability to watch on a specific quality !?
The Auto option is cool, but under some networks, it acts better than the Auto bitrate option
I've tried it myself when I raised the min bitrate :D

**Comment by mateussouzaweb** [comment]
@Bebooo43 quality level option has been added on the new player.

**Comment by Domi52** [comment]
> @Bebooo43 quality level option has been added on the new player.

In the player, I have buttons for selecting the resolution: 1080p, 720, and so on. When I hover the pointer over them, it changes, but when pressed, nothing happens, when I double-click, the text applied to the button is simply highlighted. This happens both on my TV and on my PC.

**Comment by mateussouzaweb** [comment]
@Domi52 version 1.8.0 fix the click action to actually change quality. Should work on this new version...

**Comment by tamodolo** [comment]
Sorry reviving this but I just discovered the wonders of rooting the TV. Until now I used KODI to watch CR but a native app is better. Also this app have even frame cadence and this is quite amazing (was the main reason to use KODI instead of any oficial app)

On KODI you can set it to start the stream at one fixed resolution. It have an alternative way to set the resolution to the highest available and will pick it if it's available. Can you add some options outside the player to make it default for all videos? Changing everytime is annoying

**Comment by mateussouzaweb** [comment]
For FPS cadence, see #24
