### ISSUE TITLE
Thoughts on upgrading to using a framework such as React (Enact)?

### ISSUE THREAD

**Issue by camab123** [mateussouzaweb/crunchyroll-webos#34]
I've been digging around the codebase and testing the application. It's super helpful and now my go to way to watch Crunchyroll on LG. I wanted to do some contributions to codebase such as helping with Issues and enhancement requests. However getting dev setup locally is a pain due to your dependencies on your various other repos and libraries that are not setup for mac. 

Thoughts on upgrading to using something like Enact framework? I am new to WebOS development world so might be an obvious reason why not. If not I'd like to start working on migration and get in a PR. Could lead to easier development down the road for other contributors? Could utilize their UI framework as well for quick styling work. @mateussouzaweb

**Comment by mateussouzaweb** [comment]
@camab123 Enact seems good, but I don't have plans to use it for now... the app will be redesigned in the future and we can reconsider it, but the main focus now is to increase support for new features while fixing issues.

I personally do not like the React ecosystem and started this project to learn and develop new things just outside React. In the end, I found out that WebOS has a big compatibility problem because it uses chrome versions so old that even some core JS instructions are missing... Enact does not provide the WebOS versions compatibility (at least I could not find) and that is very crucial. 

Anyway, the README instructions have been updated to recommend development with Docker. This should help with cross-platform development if you have the desire to contribute to this project.

Thanks!
